DROP TABLE T_INITIAL_TO
/
DROP TABLE T_INITIAL_TO_BACKUP
/
DROP TABLE T_INVENTORY_HISTORY_TO
/
DROP TABLE T_INVENTORY_HISTORY_TO_BACKUP
/
DROP TABLE T_INVENTORY_TO
/
DROP TABLE T_INVENTORY_TO_BACKUP
/
DROP TABLE T_INVENTORY_WORK2_TO
/
DROP TABLE T_INVENTORY_WORK_TO
/
DROP TABLE T_INVENTORY_WORK_TO_TEMP
/
DROP TABLE T_PIC_MASTER_TO
/
DROP TABLE T_PIC_MASTER_TO_BACKUP
/
DROP PACKAGE PKG_TO_APP
/
DROP PACKAGE PKG_TO_DELETE_OLD_DATA
/
DROP PACKAGE PKG_TO_DRS
/
DROP PACKAGE PKG_TO_RESET_DEMO_DATA
/
DROP SEQUENCE   T_INVENTORY_HISTORY_TO_BACKUP_SEQ
/
DROP SEQUENCE   T_INVENTORY_HISTORY_TO_SEQ
/
DROP SEQUENCE   T_INVENTORY_TO_BACKUP_SEQ
/
DROP SEQUENCE   T_INVENTORY_TO_SEQ
/
--過去データ削除JOB無効化
BEGIN
    DBMS_SCHEDULER.DISABLE('JOB_TO_DELETE_OLD_DATA');
END;
/
--過去データ削除JOB削除
BEGIN
    DBMS_SCHEDULER.DROP_JOB('JOB_TO_DELETE_OLD_DATA');
END;
/